name: '2ms Action'
description: 'Downloads and runs the Checkmarx/2ms tool on a cloned repository.'
author: 'Checkmarx'
inputs:
  repo-path:
    description: 'The path of the cloned repository.'
    required: false
    default: '.'
    # TODO: Add global flags
runs:
  using: 'composite'
  steps:
  - uses: actions/setup-node@v3
    with:
      node-version: '18'
      cache: 'yarn'
  - run: yarn install --frozen-lockfile
    shell: bash

  - name: Get latest 2ms version
    id: get-2ms-version
    shell: bash
    run: |
      VERSION=$(curl --silent "https://api.github.com/repos/Checkmarx/2ms/releases/latest" | jq -r .tag_name)
      echo "TMS_VERSION=${VERSION}" >> "$GITHUB_OUTPUT"
  - name: Cache Checkmarx/2ms
    id: cache-2ms
    uses: actions/cache@v3
    with:
      path: 2ms
      key: 2ms-tool-${{ steps.get-2ms-version.outputs.TMS_VERSION }}
  - name: Download Checkmarx/2ms
    if: ${{ steps.cache-2ms.outputs.cache-hit != 'true' }}
    shell: bash
    run: |
      curl -sL https://github.com/Checkmarx/2ms/releases/latest/download/2ms -o 2ms
      chmod +x 2ms

  - name: Run Checkmarx/2ms
    shell: bash
    run: |
      ./2ms git ${{ inputs.repo-path }} --report-path results.json
  
  - name: annotate
    if: ${{ failure() }}
    shell: bash
    run: node src/annotate.js results.json
