name: test me

on: push

jobs:
  test_me:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: ./
      with:
        log-level: debug
        exclude-rules: private-key
        regexes: "eggs,spam"
        report-paths: "results.sarif"
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      if: failure()
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: results.sarif
        # Optional category for the results
        # Used to differentiate multiple results for one commit
        category: secret-scanning
